/**
 * Builds the downloadable PDF security report using jsPDF.
 * Runs entirely in the browser — the password itself is never included.
 */

import { jsPDF } from "jspdf";
import type { Analysis } from "./password-strength";

export function downloadSecurityReport(analysis: Analysis): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const marginX = 56;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - marginX * 2;
  let y = 64;

  const line = (text: string, size = 11, bold = false, gap = 18) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    const wrapped = doc.splitTextToSize(text, contentWidth) as string[];
    wrapped.forEach((part) => {
      if (y > 780) {
        doc.addPage();
        y = 64;
      }
      doc.text(part, marginX, y);
      y += gap;
    });
  };

  const heading = (text: string) => {
    y += 10;
    line(text, 13, true, 20);
  };

  doc.setFillColor(17, 24, 46);
  doc.rect(0, 0, pageWidth, 96, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Password Security Report", marginX, 52);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Generated by Password Strength Analyzer", marginX, 72);

  doc.setTextColor(20, 20, 20);
  y = 136;

  heading("Summary");
  line(`Score: ${analysis.score} / 100`);
  line(`Strength: ${analysis.strength}`);
  line(`Entropy: ${analysis.entropy} bits (${analysis.entropyLabel})`);
  line(`Estimated crack time: ${analysis.crackTime}`);
  line(`Analysis timestamp: ${new Date(analysis.analyzedAt).toLocaleString()}`);

  heading("Requirement checklist");
  analysis.checks.forEach((check) => {
    line(`${check.passed ? "[PASS]" : "[FAIL]"}  ${check.label}`);
  });

  if (analysis.warnings.length) {
    heading("Detected weaknesses");
    analysis.warnings.forEach((warning) => line(`- ${warning}`));
  }

  heading("Suggestions");
  analysis.suggestions.forEach((tip) => line(`- ${tip}`));

  y += 14;
  doc.setTextColor(120, 120, 120);
  line(
    "Note: this report never stores or transmits your password. All analysis runs locally.",
    9,
    false,
    14,
  );

  doc.save(`password-security-report-${Date.now()}.pdf`);
}
